version: 2.0

phases:
 install:
  runtime-version:
    java: corretto11
 pre_build: 
    commands:
       - echo This is the Food Delivery Pre Build Phase
 build:
    commands:
       - echo This is the Food Delivery Build
       - mvn clean package
 post_build:
    commands:
       - echo This is the Food Delivery Post Build
artifacts:
   files:
       - target/java -jar FoodDelivery-0.0.1-SNAPSHOT.jar
